#
# site
#
url: http://m4ktub.ws
root: /

title: m4ktub
subtitle: Because some things need to be written.
description: A personal blog with pseudo-random topics that are mostly related with programming.
since: 2014

author: Cláudio Gil
author_title: Software Engineer
avatar: images/avatar.jpg
location: Portugal
follow: https://github.com/m4ktub

#
# language
#

language: en

# 
# time
#

timezone: UTC
date_format: YYYY-MM-DD
time_format: HH:mm:ss

#
# permalinks
#

permalink: posts/:year/:month/:day/:s/
permalink_defaults:

#
# news feed
#

feed:
  type: atom
  path: atom.xml
  limit: 10

# 
# paths
#

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

#
# writing
#

default_layout: post
new_post_name: :year-:month-:day-:title.md
titlecase: false
filename_case: 0
post_asset_folder: true

#
# generating
#

render_drafts: false
future: true

# pagination
per_page: 1
pagination_dir: posts/page

# archive
archive_generator:
  per_page: 0

# category
category_generator:
  per_page: 0

# tag
tag_generator:
  per_page: 0

#
# rendering
#

relative_link: false
  
marked:
  # no automatic line breaks
  gfm: false

highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

skip_render:
  # do not process javascript files (#1194)
  - '**/*.js'
  - 'experiments/**/*'

# 
# category & tags
#

default_category: uncategorized
category_map:
tag_map:

#
# site map
#

sitemap:
  path: sitemap.xml

#
# theme
#

theme: cactus

#
# comments
#

disqus_shortname: 
