#
# Jekyll Configuration File
#

# Site Information
name: m4ktub
domain: m4ktub.ws
author: Cláudio Gil
tagline: Things need to be written.
inceptionYear: 2014

# Full url format for posts
permalink: /blog/:year/:month/:day/:title

# Generation
encoding: UTF-8
markdown: kramdown
highlighter: pygments

# Github
github:
    name: m4ktub
    project: m4ktub.ws
    branch: master

# Facebook
facebook:
    name: claudio.f.gil

# Google Analytics
ga:
    id: UA-50377751-1
